pip uninstall -y vaex
pip uninstall -y vaex-arrow
pip uninstall -y vaex-astro
pip uninstall -y vaex-contrib
pip uninstall -y vaex-core
pip uninstall -y vaex-distributed
pip uninstall -y vaex-graphql
pip uninstall -y vaex-hdf5
pip uninstall -y vaex-jupyter
pip uninstall -y vaex-meta
pip uninstall -y vaex-ml
pip uninstall -y vaex-server
pip uninstall -y vaex-ui
pip uninstall -y vaex-viz